<?php
$targetList=['arduino0'];
$setvalSoft='/home/pi/Git/SerreConnectee/Server/setValue.sh';
$actuatorList=['FAN','WATER','MIST','LIGHT','HEAT'];

print('
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Serre de test</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<!--script type="text/javascript" src="view.js"></script-->

</head>
');

print ('<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Serre de test</a></h1>
');

if (sizeof($_POST) == 5 ) {
  $go = $setvalSoft.' '.$targetList[$_POST["arduinoid"]].' '.$actuatorList[$_POST["actionneur"]].' '.$_POST["etat"];
  //print_r($_POST);
  print('Envoi de la commande : '.$go);
  echo exec($go); 
}
else {
  print ('pas d\'action réalisée pour le moment.<br/>');
}

print ('
		<form id="form_103267" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Quelle action sur la serre ?</h2>
			<p>On intervient directement ici sur les actionneurs de la serre. On vérifiera le bon fonctionnement via grafana…</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="arduinoid">Quelle cible ? </label>
		<div>
		<select class="element select medium" id="arduinoid" name="arduinoid"> 
			<option value="" selected="selected"></option>');

foreach($targetList as $i => $t) {
  print('<option value="'.$i.'" ');
  if ($i==0) print(' selected="selected" ');
  print ('>'.$t.'</option>');
}

print ('
		</select>
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="actionneur">Quel actionneur ? </label>
		<span>
');

foreach($actuatorList as $i => $a) {
print ('<input id="actionneur_'.$i.'" name="actionneur" class="element radio" type="radio" value="'.$i.'" />
<label class="choice" for="actionneur_'.$i.'">'.$a.'</label>');
}

print ('
		</span> 
		</li>		<li id="li_3" >
		<label class="description" for="etat">Nouvel état ? </label>
		<span>
			<input id="etat_1" name="etat" class="element radio" type="radio" value="1" />
<label class="choice" for="etat_1">ON</label>
<input id="etat_2" name="etat" class="element radio" type="radio" value="0" />
<label class="choice" for="etat_2">OFF</label>

		</span> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="103267" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="C\'EST PARTI !" />
		</li>
			</ul>
		</form>	
		<!--div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div-->
	</div>
	<img id="bottom" src="bottom.png" alt="">
');
  
print('</body></html>');
?>
